In [1]:
#Creating Array
import numpy as np

#Scalar
scalar = np.array(5)
print("Scalar:", scalar)

#1D array (1 to 5)
arr_1d = np.array([1, 2, 3, 4, 5])
print("1D Array:", arr_1d)

#2D array (2x3) with values 10 to 60
arr_2d = np.array([[10, 20, 30],
                   [40, 50, 60]])
print("2D Array:\n", arr_2d)

Scalar: 5
1D Array: [1 2 3 4 5]
2D Array:
 [[10 20 30]
 [40 50 60]]


In [4]:
#4x4 Numpy Array
import numpy as np
random_arr = np.random.randint(0, 101, size=(4, 4))
print("Random 4x4 Array:\n", random_arr)


Random 4x4 Array:
 [[53  4 67 80]
 [31 44 25 29]
 [37 13 86 85]
 [59 61 10 30]]


In [5]:
#2D Numpy Array
import numpy as np
import pandas as pd

# Create 3x3 array
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

# Convert to DataFrame
df = pd.DataFrame(arr, columns=['A', 'B', 'C'])

print(df)

   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9
